# -*- coding: utf-8 -*-
"""Lists in Python

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TWueF4QLwRV-_vw_bJbZjzMS8qqqTROg
"""

list=[1,2,3,4]
print(list)
a=list[0]# how to access an element
print(a)
b=list[3]
c=list[-1]#how to access an element using negative indexing
print(b)
print(c)
list[0]=0  # How to update a list
print(list)
list.append(5) # append is used to add the element at the end of the list
print(list)
list.insert(0,1)#insert is used to add an elemet at specfic index
print(list)
list.extend([6,7,7,8])# it adds another DS at the end of the list
print(list)
list.remove(0)# It removes a specific value
print(list)
list.pop()#It removes the last element from the list
print(list)
list.pop(6)
print(list)# It remoevs the specific element using indexing
#list.clear()# it returns an empty list
#print(list)
list.index(2)# it returns the index value of 2
list.count(1)# it counts how many ones are there
list.sort()# sorts the elements in Ascending order
print(list)
list.sort(reverse=True)# sorts the element only in Descending Order
print(list)
list.reverse()# it reverse the list
print(list)
print(list[::-1])
new=list.copy()# it copys the list
print(new)